add log files

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -247,19 +247,24 @@ variables:
     - python ~/bim2sim-coding/bim2sim/plugins/PluginTEASER/test/regression/prepare_regression_tests.py
     # TODO for EP image install .idf file (see previous pipeline)
     # use  xvfb-run -n 77  command if dymola image is used
+    # use set +e to make sure the pipeline does not stop when the job returns exit code 1
     - |
+      set +e
       if [[ "$CI_JOB_IMAGE" == *"dymola"* ]]; then
         xvfb-run -n 77 coverage run -m unittest discover ~/bim2sim-coding/bim2sim/plugins/${plugin}/test/regression
       else
         coverage run -m unittest discover ~/bim2sim-coding/bim2sim/plugins/${plugin}/test/regression
       fi
+      test_exit_code=$?
+      set -e
     - ls -la ./
     - ls -la /builds/EBC/EBC_all/github_ci/bim2sim
-    - ls -la /builds/EBC/EBC_all/github_ci/bim2sim/logs
+    - ls -la /builds/EBC/EBC_all/github_ci/bim2sim/logs || true
     - mkdir -p /builds/EBC/EBC_all/github_ci/bim2sim/logs/
-    - cp *.log /builds/EBC/EBC_all/github_ci/bim2sim/logs/
+    - cp *.log /builds/EBC/EBC_all/github_ci/bim2sim/logs/ || true
     - ls -la /builds/EBC/EBC_all/github_ci/bim2sim
     - ls -la /builds/EBC/EBC_all/github_ci/bim2sim/logs
+    - exit $test_exit_code
   artifacts:
     paths:
   #    - logs/*
